# Generated by Django 2.1 on 2019-04-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biografia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Biografía', max_length=255)),
                ('contenido', models.TextField(help_text='Descripcion Biografía')),
                ('titulo_dos', models.CharField(blank=True, help_text='Influencias', max_length=20, null=True)),
                ('contenido_dos', models.CharField(blank=True, help_text='Géneros Musicales', max_length=255, null=True)),
                ('etiqueta_uno', models.CharField(blank=True, help_text='Influencia Musical Uno', max_length=20, null=True)),
                ('etiqueta_dos', models.CharField(blank=True, help_text='Influencia Musical Dos', max_length=20, null=True)),
                ('etiqueta_tres', models.CharField(blank=True, help_text='Influencia Musical Tres', max_length=20, null=True)),
                ('etiqueta_cuatro', models.CharField(blank=True, help_text='Influencia Musical Cuatro', max_length=20, null=True)),
                ('slug', models.SlugField(editable=False)),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'ordering': ('titulo',),
            },
        ),
    ]
